### PR TITLE
Ui

### PR DESCRIPTION
**Pull request by ab-fpmi**

### CODE REVIEW

**Comment by skateray17** [comment]
I really like that work, just some notes: there is a vertical scroll for desktop with low resolution. Also, for now, there is no possibility to filter posts in mobile view?

**Comment by ab-fpmi** [comment]
> I really like that work, just some notes: there is a vertical scroll for desktop with low resolution. 

I totally can fix footer to the bottom of the screen and scroll only the central area. I don't actually like how it looks, though. The footer is not that important for users and it will eat up some screen space. But I can do it, should I?

> Also, for now, there is no possibility to filter posts in mobile view?
My idea is to pop up modal with filtering form by clicking the "filter" button. That will save some precious space on mobile screens.

**Comment by skateray17** [comment]
Sorry, I meant horizontal scroll

**Comment by ab-fpmi** [comment]
Oh, I see. So, I've changed breakpoints a bit. Not really happy with the result, but for now it should cut it.

**Pull request merged**
